### ISSUE TITLE
我重新用环境准备的方法下载为什么它还会去找d盘的python

### ISSUE THREAD

**Issue by 23spiteful** [neolee/wop-ecnu-pub#49]
PS C:\Users\74092> pip install termcolor
Fatal error in launcher: Unable to create process using '"d:\python3.7.4\python.exe"  "D:\python3.7.4\Scripts\pip.exe" install termcolor': ???????????

**Comment by 23spiteful** [comment]
我把d盘的python文件全删了，重装了pip
PS C:\Users\74092> jupyter lab
Traceback (most recent call last):
  File "c:\users\74092\scoop\apps\python\current\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\74092\scoop\apps\python\current\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\74092\scoop\apps\python\current\Scripts\jupyter.exe\__main__.py", line 7, in <module>
  File "c:\users\74092\scoop\apps\python\current\lib\site-packages\jupyter_core\command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "c:\users\74092\scoop\apps\python\current\lib\site-packages\jupyter_core\command.py", line 133, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-lab` not found.
这又是为什么

**Comment by neolee** [comment]
你装的是 jupyter 还是 jupyterlab？

**Comment by 23spiteful** [comment]
哦~现在可以了
